name: CI - Bun + Zero Trust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar código
        uses: actions/checkout@v4

      - name: Instalar Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Instalar dependencias
        run: bun install --no-cache

      - name: Ejecutar Linter
        run: bun run lint

      - name: Validar formato Prettier
        run: bun run format

      - name: Ejecutar Gitleaks (detección de secretos)
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source=. --no-banner
